const SUPABASE_URL='https://frvxdqdkoaozuvmrqdkl.supabase.co';
const SUPABASE_KEY='sb_publishable_3SehkvZWuoHkQmTivP6dYw_VIijLcf5';
const LOCAL_KEY='moneyology:standalone:v1';
let sb=null,session=null,syncTimer=null,loadingCloud=false;
let state={transactions:[],debts:[],accounts:[],savings:[],settings:{currency:'$',paycheckAmount:0,periodStart:'',periodEnd:''}};
let calDate=new Date(),miniDate=new Date(),activeFilter='All';
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
const money=v=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(Number(v)||0);
const uid=()=>crypto.randomUUID?crypto.randomUUID():Date.now().toString(36)+Math.random().toString(36).slice(2);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#39;'}[c]));
const sum=(a,fn=x=>x)=>a.reduce((n,x)=>n+(Number(fn(x))||0),0);
function loadLocal(){try{const raw=localStorage.getItem(LOCAL_KEY);if(raw){const parsed=JSON.parse(raw);state={...state,...parsed,settings:{...state.settings,...(parsed.settings||{})}}}}catch(e){console.warn(e)}}
function saveLocal(queue=true){localStorage.setItem(LOCAL_KEY,JSON.stringify(state));renderAll();if(queue)queueSync()}
function setSync(text,kind=''){const el=$('#syncStatus');if(el){el.textContent=text;el.className='sync '+kind}}
function toast(text){const el=$('#toast');if(!el)return;el.textContent=text;el.classList.remove('hidden');clearTimeout(el._t);el._t=setTimeout(()=>el.classList.add('hidden'),2300)}
function queueSync(){if(!session||!sb||loadingCloud)return;clearTimeout(syncTimer);setSync('Saving…','busy');syncTimer=setTimeout(pushCloud,550)}
async function pushCloud(){if(!session||!sb||loadingCloud)return;const {error}=await sb.from('user_budget_state').upsert({user_id:session.user.id,payload:state,updated_at:new Date().toISOString()},{onConflict:'user_id'});setSync(error?'Sync error':'Synced',error?'':'ok')}
async function pullCloud(){if(!session||!sb)return;setSync('Checking cloud…','busy');const {data,error}=await sb.from('user_budget_state').select('payload').eq('user_id',session.user.id).maybeSingle();if(error){setSync('Sync error');return}if(data?.payload){loadingCloud=true;state={...state,...data.payload,settings:{...state.settings,...(data.payload.settings||{})}};localStorage.setItem(LOCAL_KEY,JSON.stringify(state));loadingCloud=false;renderAll();setSync('Synced','ok')}else await pushCloud()}
function navTo(name){$$('.section').forEach(x=>x.classList.toggle('active',x.dataset.section===name));$$('.nav button[data-nav]').forEach(x=>x.classList.toggle('active',x.dataset.nav===name));const b=$(`.nav button[data-nav="${name}"]`);if($('#pageTitle'))$('#pageTitle').textContent=b?b.textContent.trim():'Moneyology';$('#sidebar')?.classList.remove('open');localStorage.setItem('moneyology:last-section',name);if(name==='calendar')renderCalendar()}
function txByCategory(cat){return state.transactions.filter(t=>t.category===cat)}
function incomeTx(){return state.transactions.filter(t=>t.type==='income')}
function colorFor(cat){return {'Income':'#4fcacb','Savings':'#b65ad5','Bills':'#ff943e','Subscriptions':'#ff648f','Debt Payments':'#f55c8d'}[cat]||'#aaa'}
function getTotals(){return {income:sum(incomeTx(),t=>t.amount),savings:sum(txByCategory('Savings'),t=>t.amount),bills:sum(txByCategory('Bills'),t=>t.amount),subs:sum(txByCategory('Subscriptions'),t=>t.amount),debtPay:sum(txByCategory('Debt Payments'),t=>t.amount)}}
function renderPaycheck(){
 const t=getTotals(); const planned=t.savings+t.bills+t.subs+t.debtPay; const paycheck=Number(state.settings.paycheckAmount)||t.income||0; const left=paycheck-planned; const pct=paycheck?Math.min(100,Math.max(0,planned/paycheck*100)):0;
 const summary=$('#paycheckSummary'); if(summary)summary.innerHTML=`<div class="summary-block income"><small>INCOME</small><strong>${money(t.income)}</strong></div><div class="summary-block savings"><small>SAVINGS</small><strong>${money(t.savings)}</strong></div><div class="summary-block bills"><small>BILLS</small><strong>${money(t.bills)}</strong></div><div class="summary-block subscriptions"><small>SUBSCRIPTIONS</small><strong>${money(t.subs)}</strong></div><div class="summary-block debt"><small>DEBT PAYMENTS</small><strong>${money(t.debtPay)}</strong></div><div class="summary-progress"><div class="track"><i style="width:${pct}%"></i></div><p><span>Left to budget: <b>${money(left)}</b></span><span>Planned ${money(planned)} of ${money(paycheck)} · ${pct.toFixed(0)}%</span></p></div>`;
 if($('#paycheckAmount'))$('#paycheckAmount').value=paycheck||''; if($('#periodStart'))$('#periodStart').value=state.settings.periodStart||''; if($('#periodEnd'))$('#periodEnd').value=state.settings.periodEnd||''; if($('#leftBudget'))$('#leftBudget').textContent=money(left);
 const rows=[['Income',t.income],['Savings',t.savings],['Bills',t.bills],['Subscriptions',t.subs],['Debt Payments',t.debtPay]]; const h=$('#breakdownRows'); if(h)h.innerHTML=rows.map(([n,v])=>`<div class="break-row"><span><i class="dot" style="background:${colorFor(n)}"></i>${n}</span><b>${paycheck?Math.round(v/paycheck*100):0}%</b><input value="${Number(v||0).toFixed(2)}" readonly></div>`).join('');
 if($('#breakdownDonut'))$('#breakdownDonut').style.background=`conic-gradient(#4fcacb 0 ${Math.min(100,paycheck?t.income/paycheck*100:0)}%,#b65ad5 0 ${Math.min(100,paycheck?(t.income+t.savings)/paycheck*100:0)}%,#ff943e 0 ${Math.min(100,paycheck?(t.income+t.savings+t.bills)/paycheck*100:0)}%,#ff648f 0 ${Math.min(100,paycheck?(t.income+t.savings+t.bills+t.subs)/paycheck*100:0)}%,#f55c8d 0 100%)`;
 const bd=$('#breakdownDonut span'); if(bd)bd.textContent=`${pct.toFixed(0)}%`;
 renderIncomeCard(t.income); renderSavingsCard(); renderCategoryCard('Bills','#billTable','#totalBills','#billProgress','#billDonut'); renderCategoryCard('Subscriptions','#subscriptionTable','#totalSubscriptions','#subProgress','#subDonut'); renderCategoryCard('Debt Payments','#debtPaymentTable','#totalDebtPayments','#debtProgress','#debtPayDonut');
}
function miniTable(items,type='transaction'){if(!items.length)return '<div class="empty">Nothing planned yet.</div>';return `<div class="table-head"><span>NAME</span><span>${type==='savings'?'SAVED':'DATE'}</span><span>${type==='savings'?'GOAL':'AMOUNT'}</span></div>`+items.slice(0,5).map(x=>`<div class="table-row"><span>${esc(x.name)}</span><span>${type==='savings'?money(x.balance):esc(x.date||'—')}</span><strong>${type==='savings'?money(x.goal):money(x.amount)}</strong></div>`).join('')}
function renderIncomeCard(total){if($('#incomeTotalInput'))$('#incomeTotalInput').value=Number(total).toFixed(2);if($('#incomeReceived'))$('#incomeReceived').textContent=money(total);if($('#incomeExpected'))$('#incomeExpected').textContent=money(total);if($('#incomeDiff'))$('#incomeDiff').textContent=money(0);if($('#incomeProgress'))$('#incomeProgress').style.width=total?'100%':'0%';if($('#incomeTable'))$('#incomeTable').innerHTML=miniTable(incomeTx())}
function renderSavingsCard(){const saved=sum(state.savings,s=>s.balance),goal=sum(state.savings,s=>s.goal),left=Math.max(0,goal-saved),pct=goal?Math.min(100,saved/goal*100):0;if($('#savingsTotalInput'))$('#savingsTotalInput').value=Number(saved).toFixed(2);if($('#savedNow'))$('#savedNow').textContent=money(saved);if($('#savedGoal'))$('#savedGoal').textContent=money(goal);if($('#savedLeft'))$('#savedLeft').textContent=money(left);if($('#savingsProgress'))$('#savingsProgress').style.width=pct+'%';if($('#savingsMiniTable'))$('#savingsMiniTable').innerHTML=miniTable(state.savings,'savings');if($('#savingsDonut'))$('#savingsDonut').style.background=`conic-gradient(#c378d6 0 ${pct}%,#eee ${pct}% 100%)`;if($('#savingsDonut span'))$('#savingsDonut span').textContent=pct.toFixed(0)+'%'}
function renderCategoryCard(cat,tableSel,totalSel,progSel,donutSel){const items=txByCategory(cat),total=sum(items,t=>t.amount);const totalEl=$(totalSel),tableEl=$(tableSel),progEl=$(progSel),donutEl=$(donutSel);if(totalEl)totalEl.textContent=money(total);if(tableEl)tableEl.innerHTML=miniTable(items);const pct=items.length?Math.min(100,items.filter(x=>x.paid).length/items.length*100):0;if(progEl)progEl.style.width=pct+'%';if(donutEl)donutEl.style.background=`conic-gradient(${colorFor(cat)} 0 ${pct}%,#eee ${pct}% 100%)`;const dspan=$(donutSel+' span');if(dspan)dspan.textContent=pct.toFixed(0)+'%'}
function renderRows(host,items){if(!host)return;if(!items.length){host.innerHTML='<div class="empty">Nothing here yet.</div>';return}host.innerHTML=items.map(t=>`<div class="row-card"><div><div class="name">${esc(t.name)}</div><div class="meta">${esc(t.category||'Other Planned')} · ${esc(t.frequency||'One-time')} · ${esc(t.date||'No date')} ${t.priority?`· ${esc(t.priority)}`:''}</div></div><div class="amount ${t.type==='income'?'in':'out'}">${t.type==='income'?'+':'-'}${money(t.amount)}</div></div>`).join('')}
function renderTransactions(){const sorted=[...state.transactions].sort((a,b)=>(a.date||'').localeCompare(b.date||''));renderRows($('#transactionList'),sorted);renderRows($('#billListPage'),sorted.filter(t=>t.category==='Bills'));renderRows($('#subscriptionListPage'),sorted.filter(t=>t.category==='Subscriptions'))}
function renderSavings(){const saved=sum(state.savings,s=>s.balance),goal=sum(state.savings,s=>s.goal),left=Math.max(0,goal-saved),done=state.savings.filter(s=>Number(s.balance)>=Number(s.goal)&&Number(s.goal)>0).length;if($('#savingsSummary'))$('#savingsSummary').innerHTML=`<div><small>TOTAL GOAL AMOUNT</small><strong style="color:#9345a8">${money(goal)}</strong></div><div><small>SAVED AMOUNT</small><strong style="color:#0c9697">${money(saved)}</strong></div><div><small>LEFT TO SAVE</small><strong style="color:#ff3f82">${money(left)}</strong></div><div><small>REACHED</small><strong style="color:#ef7a16">${done} / ${state.savings.length}</strong></div>`;const host=$('#savingsList');if(!host)return;host.innerHTML=state.savings.length?state.savings.map((s,i)=>{const p=s.goal?Math.min(100,Number(s.balance||0)/Number(s.goal)*100):0;const remain=Math.max(0,Number(s.goal||0)-Number(s.balance||0));const target=s.targetDate?new Date(s.targetDate+'T12:00:00'):null;const now=new Date();const months=target?Math.max(1,(target.getFullYear()-now.getFullYear())*12+target.getMonth()-now.getMonth()):1;const monthly=remain/months;return `<div class="fund-card ${i%2?'orange':''}"><div class="fund-top"><div><div class="fund-title">${esc(s.name)}</div><small>${esc(s.account||'No account linked')}</small></div><div class="fund-amount">${money(s.balance)}<small style="display:block;font-size:10px;color:#8f858c">SAVED</small></div></div><div class="fund-progress"><i style="width:${p}%"></i></div><div class="fund-info"><div><small>PERIOD</small><strong>${s.targetDate?esc(s.targetDate):'No target date'}</strong></div><div><small>STATUS</small><strong>${p>=100?'Reached 🎉':p.toFixed(0)+'% saved'}</strong></div><div><small>LEFT TO SAVE</small><strong>${money(remain)}</strong></div><div><small>MONTHLY TARGET</small><strong>${money(monthly)}/mo</strong></div></div></div>`}).join(''):'<div class="empty">Add your first savings fund.</div>'}
function renderDebts(){const host=$('#debtList');if(!host)return;host.innerHTML=state.debts.length?state.debts.map((d,i)=>{const o=Math.max(0,Number(d.originalBalance)||0),c=Math.max(0,Number(d.currentBalance)||0),paid=Math.max(0,o-c),p=o?Math.min(100,paid/o*100):0;return `<div class="fund-card ${i%2?'orange':''}"><div class="fund-top"><div><div class="fund-title">${esc(d.name)}</div><small>${Number(d.apr||0).toFixed(2)}% APR · ${esc(d.frequency||'Monthly')}</small></div><div class="fund-amount">${money(c)}<small style="display:block;font-size:10px">BALANCE</small></div></div><div class="fund-progress"><i style="width:${p}%"></i></div><div class="fund-info"><div><small>ORIGINAL</small><strong>${money(o)}</strong></div><div><small>PAID</small><strong>${money(paid)}</strong></div><div><small>REGULAR PAYMENT</small><strong>${money(d.payment)}</strong></div><div><small>LIFETIME PROGRESS</small><strong>${p.toFixed(0)}%</strong></div></div></div>`}).join(''):'<div class="empty">Add your first debt.</div>'}
function renderAccounts(){const h=$('#accountList');if(!h)return;h.innerHTML=state.accounts.length?state.accounts.map(a=>`<div class="row-card"><div><div class="name">${esc(a.name)}</div><div class="meta">${esc(a.type||'Account')}</div></div><div class="amount">${money(a.balance)}</div></div>`).join(''):'<div class="empty">No accounts added yet.</div>'}
function renderReports(){const t=getTotals(),debt=sum(state.debts,d=>d.currentBalance),sav=sum(state.savings,s=>s.balance);if($('#reportCards'))$('#reportCards').innerHTML=`<div><small>PLANNED INCOME</small><strong>${money(t.income)}</strong></div><div><small>PLANNED OUTFLOW</small><strong>${money(t.savings+t.bills+t.subs+t.debtPay)}</strong></div><div><small>CURRENT DEBT</small><strong>${money(debt)}</strong></div><div><small>SAVINGS</small><strong>${money(sav)}</strong></div>`}
function addMonthsSafe(date,n){const d=new Date(date);const day=d.getDate();d.setDate(1);d.setMonth(d.getMonth()+n);d.setDate(Math.min(day,new Date(d.getFullYear(),d.getMonth()+1,0).getDate()));return d}
function occurrences(tx,y,m){if(!tx.date)return[];let d=new Date(tx.date+'T12:00:00');if(isNaN(d))return[];const end=new Date(y,m+1,0,23,59,59),out=[],f=tx.frequency||'One-time';if(f==='One-time')return d.getFullYear()===y&&d.getMonth()===m?[d]:[];let guard=0;while(d<=end&&guard++<1000){if(d.getFullYear()===y&&d.getMonth()===m)out.push(new Date(d));if(f==='Weekly')d=new Date(d.getFullYear(),d.getMonth(),d.getDate()+7,12);else if(f==='Bi-weekly')d=new Date(d.getFullYear(),d.getMonth(),d.getDate()+14,12);else if(f==='Monthly')d=addMonthsSafe(d,1);else if(f==='Quarterly')d=addMonthsSafe(d,3);else if(f==='Yearly')d=new Date(d.getFullYear()+1,d.getMonth(),d.getDate(),12);else break}return out}
function filterTx(t){if(activeFilter==='All')return true;if(activeFilter==='Bills')return t.category==='Bills';if(activeFilter==='Subscriptions')return t.category==='Subscriptions';if(activeFilter==='Debts')return t.category==='Debt Payments';if(activeFilter==='Savings')return t.category==='Savings';if(activeFilter==='Paychecks')return t.type==='income';return true}
function renderCalendar(){const host=$('#calendarHost'),stats=$('#calendarStats'),filters=$('#calendarFilters');if(!host||!stats||!filters)return;const y=calDate.getFullYear(),m=calDate.getMonth(),first=new Date(y,m,1),days=new Date(y,m+1,0).getDate(),start=(first.getDay()+6)%7,today=new Date();let cells='';for(let i=0;i<start;i++)cells+='<div class="cal-cell outside"></div>';for(let d=1;d<=days;d++){const items=[];state.transactions.forEach(t=>{if(filterTx(t)&&occurrences(t,y,m).some(o=>o.getDate()===d))items.push(t)});cells+=`<div class="cal-cell" data-day="${d}"><div class="cal-num">${d}</div>${items.slice(0,5).map(t=>`<span class="cal-chip ${t.type==='income'?'income':String(t.category||'').toLowerCase().replace(/\s+/g,'-')}">${esc(t.name)} · ${money(t.amount)}</span>`).join('')}</div>`}let inc=0,out=0;state.transactions.filter(filterTx).forEach(t=>{const n=occurrences(t,y,m).length;if(t.type==='income')inc+=Number(t.amount||0)*n;else out+=Number(t.amount||0)*n});const balance=sum(state.accounts,a=>a.balance),projected=balance+inc-out;stats.innerHTML=`<div><small>CURRENT BALANCE</small><strong style="color:#078a91">${money(balance)}</strong></div><div><small>PROJECTED BALANCE</small><strong style="color:#ff3f82">${money(projected)}</strong></div><div><small>PLANNED OUT</small><strong style="color:#c77c00">${money(out)}</strong></div><div><small>TODAY IS</small><strong style="color:#9250ad">${today.toLocaleDateString('en-US',{month:'long',day:'numeric'})}</strong></div>`;filters.innerHTML=['All','Bills','Subscriptions','Debts','Savings','Paychecks'].map(x=>`<button type="button" data-filter="${x}" class="${x===activeFilter?'active':''}">${x}</button>`).join('');host.innerHTML=`<div class="month-nav"><button data-cal="prev">‹ Prev</button><strong>${first.toLocaleDateString('en-US',{month:'long',year:'numeric'})}</strong><button data-cal="next">Next ›</button></div><div class="weekday-row"><span>Monday</span><span>Tuesday</span><span>Wednesday</span><span>Thursday</span><span>Friday</span><span>Saturday</span><span>Sunday</span></div><div class="big-calendar">${cells}</div>`;host.querySelector('[data-cal=prev]').onclick=()=>{calDate=new Date(y,m-1,1);miniDate=new Date(calDate);renderCalendar();renderMiniCalendar()};host.querySelector('[data-cal=next]').onclick=()=>{calDate=new Date(y,m+1,1);miniDate=new Date(calDate);renderCalendar();renderMiniCalendar()};filters.querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>{activeFilter=b.dataset.filter;renderCalendar()});host.querySelectorAll('.cal-cell[data-day]').forEach(c=>c.onclick=()=>openTransaction({date:`${y}-${String(m+1).padStart(2,'0')}-${String(c.dataset.day).padStart(2,'0')}`}))}
function renderMiniCalendar(){const h=$('#miniCalendar');if(!h)return;const y=miniDate.getFullYear(),m=miniDate.getMonth(),first=new Date(y,m,1),days=new Date(y,m+1,0).getDate(),start=(first.getDay()+6)%7,today=new Date();let cells='';for(let i=0;i<start;i++)cells+='<i></i>';for(let d=1;d<=days;d++){const t=today.getFullYear()===y&&today.getMonth()===m&&today.getDate()===d;cells+=`<b class="${t?'today':''}" data-mini-day="${d}">${d}</b>`}h.innerHTML=`<div class="mini-head"><button data-mini="prev">‹</button><strong>${first.toLocaleDateString('en-US',{month:'long',year:'numeric'})}</strong><button data-mini="next">›</button></div><div class="mini-days"><em>M</em><em>T</em><em>W</em><em>T</em><em>F</em><em>S</em><em>S</em>${cells}</div>`;h.querySelector('[data-mini=prev]').onclick=()=>{miniDate=new Date(y,m-1,1);renderMiniCalendar()};h.querySelector('[data-mini=next]').onclick=()=>{miniDate=new Date(y,m+1,1);renderMiniCalendar()};h.querySelectorAll('[data-mini-day]').forEach(b=>b.onclick=()=>{calDate=new Date(y,m,Number(b.dataset.miniDay));navTo('calendar');renderCalendar()})}
function renderAll(){renderPaycheck();renderTransactions();renderSavings();renderDebts();renderAccounts();renderReports();renderCalendar();renderMiniCalendar()}
function openTransaction(prefill={}){const m=$('#transactionModal'),f=$('#transactionForm');m.classList.remove('hidden');f.reset();if(prefill.category)f.elements.category.value=prefill.category;if(prefill.type)f.elements.type.value=prefill.type;if(prefill.date)f.elements.date.value=prefill.date}
function closeTransaction(){$('#transactionModal').classList.add('hidden')}
function bindForms(){
 $('#transactionForm').addEventListener('submit',e=>{e.preventDefault();const submit=e.submitter;const f=new FormData(e.currentTarget);state.transactions.push({id:uid(),name:String(f.get('name')).trim(),amount:Number(f.get('amount')),type:f.get('type'),category:f.get('category'),date:f.get('date'),priority:f.get('priority'),frequency:f.get('frequency'),notes:f.get('notes'),paid:submit?.value==='paid'});saveLocal();if(submit?.value==='another'){e.currentTarget.reset();toast('Saved — add another ✨')}else{closeTransaction();toast(submit?.value==='paid'?'Saved & marked paid ✓':'Transaction saved ✨')}});
 $$('.quick-add[data-quick]').forEach(form=>form.addEventListener('submit',e=>{e.preventDefault();const f=new FormData(form),kind=form.dataset.quick;if(kind==='income')state.transactions.push({id:uid(),name:String(f.get('name')).trim(),amount:Number(f.get('amount')),type:'income',category:'Income',date:new Date().toISOString().slice(0,10),frequency:'One-time'});else state.transactions.push({id:uid(),name:String(f.get('name')).trim(),amount:Number(f.get('amount')),type:'expense',category:kind,date:f.get('date')||'',frequency:'One-time'});saveLocal();form.reset();toast('Added to planner ✨')}));
 $('#quickSavings').addEventListener('submit',e=>{e.preventDefault();const f=new FormData(e.currentTarget);state.savings.push({id:uid(),name:String(f.get('name')).trim(),balance:0,goal:Number(f.get('goal')),targetDate:''});saveLocal();e.currentTarget.reset();toast('Savings goal added')});
 $('#savingsForm').addEventListener('submit',e=>{e.preventDefault();const f=new FormData(e.currentTarget);state.savings.push({id:uid(),name:String(f.get('name')).trim(),balance:Number(f.get('balance')),goal:Number(f.get('goal')),targetDate:f.get('targetDate')||''});saveLocal();e.currentTarget.reset();e.currentTarget.classList.add('hidden');toast('Savings fund saved')});
 $('#debtForm').addEventListener('submit',e=>{e.preventDefault();const f=new FormData(e.currentTarget);state.debts.push({id:uid(),name:String(f.get('name')).trim(),originalBalance:Number(f.get('originalBalance')),currentBalance:Number(f.get('currentBalance')),apr:Number(f.get('apr')||0),payment:Number(f.get('payment')||0),frequency:f.get('frequency')});saveLocal();e.currentTarget.reset();toast('Debt saved')});
 $('#accountForm').addEventListener('submit',e=>{e.preventDefault();const f=new FormData(e.currentTarget);state.accounts.push({id:uid(),name:String(f.get('name')).trim(),type:f.get('type'),balance:Number(f.get('balance'))});saveLocal();e.currentTarget.reset();toast('Account saved')});
 $('#paycheckAmount').addEventListener('change',e=>{state.settings.paycheckAmount=Number(e.target.value)||0;saveLocal()});$('#periodStart').addEventListener('change',e=>{state.settings.periodStart=e.target.value;saveLocal()});$('#periodEnd').addEventListener('change',e=>{state.settings.periodEnd=e.target.value;saveLocal()});
}
function authView(sess){session=sess||null;if(session){$('#authOverlay').classList.add('hidden');$('#signedIn').textContent=`Signed in as ${session.user.email}`;$('#signOutBtn').classList.remove('hidden');pullCloud()}else{$('#authOverlay').classList.remove('hidden');$('#signedIn').textContent='Not signed in';$('#signOutBtn').classList.add('hidden');setSync('Sign in to sync')}}
async function initAuth(){try{const mod=await import('https://esm.sh/@supabase/supabase-js@2');sb=mod.createClient(SUPABASE_URL,SUPABASE_KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});const {data}=await sb.auth.getSession();authView(data.session);sb.auth.onAuthStateChange((_e,s)=>setTimeout(()=>authView(s),0))}catch(e){console.error(e);$('#authMsg').textContent='Login could not load. Refresh and try again.'}}
function bindAuth(){$('#signInBtn').onclick=async()=>{if(!sb)return;const email=$('#email').value.trim(),password=$('#password').value;$('#authMsg').textContent='Signing in…';const {error}=await sb.auth.signInWithPassword({email,password});$('#authMsg').textContent=error?error.message:'Signed in.'};$('#signUpBtn').onclick=async()=>{if(!sb)return;const email=$('#email').value.trim(),password=$('#password').value;if(!email||password.length<6){$('#authMsg').textContent='Enter an email and a password with at least 6 characters.';return}$('#authMsg').textContent='Creating account…';const {data,error}=await sb.auth.signUp({email,password,options:{emailRedirectTo:location.origin+location.pathname}});if(error){$('#authMsg').textContent=error.message;return}$('#authMsg').innerHTML=data?.session?'Account created — you’re signed in! 💖':`<b>Hey! 💌 Go confirm your email!</b><br>We sent a confirmation link to ${esc(email)}. Then come back and press Sign in.`};$('#signOutBtn').onclick=()=>sb?.auth.signOut()}
function init(){loadLocal();renderAll();bindForms();bindAuth();$$('.nav button[data-nav]').forEach(b=>b.onclick=()=>navTo(b.dataset.nav));$$('[data-action="add-transaction"]').forEach(b=>b.onclick=()=>openTransaction({category:b.dataset.prefill||''}));$$('[data-close-modal]').forEach(x=>x.onclick=closeTransaction);$('#openSavingsForm').onclick=()=>$('#savingsForm').classList.toggle('hidden');$('#mobileMenu').onclick=()=>$('#sidebar').classList.toggle('open');navTo(localStorage.getItem('moneyology:last-section')||'dashboard');initAuth();if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(console.warn)}
document.addEventListener('DOMContentLoaded',init);