const SUPABASE_URL='https://frvxdqdkoaozuvmrqdkl.supabase.co';
const SUPABASE_KEY='sb_publishable_3SehkvZWuoHkQmTivP6dYw_VIijLcf5';
const LOCAL_KEY='moneyology:standalone:v1';
let sb=null,session=null,syncTimer=null,loadingCloud=false;
let state={transactions:[],debts:[],accounts:[],savings:[],settings:{currency:'$'}};
let calDate=new Date(),activeFilter='All',miniDate=new Date();
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
const money=v=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(Number(v)||0);
const uid=()=>crypto.randomUUID?crypto.randomUUID():Date.now().toString(36)+Math.random().toString(36).slice(2);
const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const sum=(a,fn=x=>x)=>a.reduce((n,x)=>n+(Number(fn(x))||0),0);
function loadLocal(){try{const raw=localStorage.getItem(LOCAL_KEY);if(raw)state={...state,...JSON.parse(raw)}}catch(e){console.warn(e)}}
function saveLocal(queue=true){localStorage.setItem(LOCAL_KEY,JSON.stringify(state));renderAll();if(queue)queueSync()}
function setSync(text,kind=''){const el=$('#syncStatus');if(el){el.textContent=text;el.className='sync '+kind}}
function toast(text){const el=$('#toast');el.textContent=text;el.classList.remove('hidden');clearTimeout(el._t);el._t=setTimeout(()=>el.classList.add('hidden'),2400)}
function queueSync(){if(!session||!sb||loadingCloud)return;clearTimeout(syncTimer);setSync('Saving…','busy');syncTimer=setTimeout(pushCloud,600)}
async function pushCloud(){if(!session||!sb||loadingCloud)return;const {error}=await sb.from('user_budget_state').upsert({user_id:session.user.id,payload:state,updated_at:new Date().toISOString()},{onConflict:'user_id'});setSync(error?'Sync error':'Synced',error?'':'ok')}
async function pullCloud(){if(!session||!sb)return;setSync('Checking cloud…','busy');const {data,error}=await sb.from('user_budget_state').select('payload').eq('user_id',session.user.id).maybeSingle();if(error){setSync('Sync error');return}if(data?.payload){loadingCloud=true;state={...state,...data.payload};localStorage.setItem(LOCAL_KEY,JSON.stringify(state));loadingCloud=false;renderAll();setSync('Synced','ok')}else await pushCloud()}
function navTo(name){$$('.section').forEach(x=>x.classList.toggle('active',x.dataset.section===name));$$('.nav button[data-nav]').forEach(x=>x.classList.toggle('active',x.dataset.nav===name));const b=$(`.nav button[data-nav="${name}"]`);$('#pageTitle').textContent=b?b.textContent.trim():'Moneyology';$('#sidebar').classList.remove('open');localStorage.setItem('moneyology:last-section',name);if(name==='calendar')renderCalendar()}
function renderRows(host,items){if(!host)return;if(!items.length){host.innerHTML='<div class="empty">Nothing here yet.</div>';return}host.innerHTML=items.map(t=>`<div class="row-card"><div><div class="name">${esc(t.name)}</div><div class="meta">${esc(t.category||'Other Planned')} · ${esc(t.frequency||'One-time')} · ${esc(t.date||'No date')}</div></div><div class="amount ${t.type==='income'?'in':'out'}">${t.type==='income'?'+':'-'}${money(t.amount)}</div></div>`).join('')}
function renderDashboard(){const income=sum(state.transactions.filter(t=>t.type==='income'),t=>t.amount),out=sum(state.transactions.filter(t=>t.type!=='income'),t=>t.amount),debt=sum(state.debts,d=>d.currentBalance),sav=sum(state.savings,s=>s.balance);$('#sumIncome').textContent=money(income);$('#sumOut').textContent=money(out);$('#sumDebt').textContent=money(debt);$('#sumSavings').textContent=money(sav);$('#subscriptionCount').textContent=state.transactions.filter(t=>t.category==='Subscriptions').length;renderRows($('#recentTransactions'),[...state.transactions].sort((a,b)=>(a.date||'').localeCompare(b.date||'')).slice(0,6));$('#insightCards').innerHTML=`<div class="summary pink"><small>PLANNED INCOME</small><strong>${money(income)}</strong></div><div class="summary peach"><small>PLANNED OUT</small><strong>${money(out)}</strong></div><div class="summary lav"><small>DEBT</small><strong>${money(debt)}</strong></div><div class="summary mint"><small>SAVINGS</small><strong>${money(sav)}</strong></div>`}
function renderTransactions(){renderRows($('#transactionList'),[...state.transactions].sort((a,b)=>(a.date||'').localeCompare(b.date||'')))}
function renderAccounts(){const h=$('#accountList');h.innerHTML=state.accounts.length?state.accounts.map(a=>`<div class="row-card"><div><div class="name">${esc(a.name)}</div><div class="meta">${esc(a.type)}</div></div><div class="amount">${money(a.balance)}</div></div>`).join(''):'<div class="empty">No accounts added yet.</div>'}
function renderSavings(){const h=$('#savingsList');h.innerHTML=state.savings.length?state.savings.map(s=>{const p=s.goal?Math.min(100,Number(s.balance||0)/Number(s.goal)*100):0;return `<div class="debt"><div class="debt-top"><div><div class="debt-name">${esc(s.name)}</div><div class="muted">Goal ${money(s.goal)}</div></div><div class="amount">${money(s.balance)}</div></div><div class="progress"><span style="width:${p}%"></span></div><div class="progress-copy">${p.toFixed(0)}% funded</div></div>`}).join(''):'<div class="empty">No savings funds yet.</div>'}
function renderDebts(){const h=$('#debtList');h.innerHTML=state.debts.length?state.debts.map(d=>{const o=Math.max(0,Number(d.originalBalance)||0),c=Math.max(0,Number(d.currentBalance)||0),paid=Math.max(0,o-c),p=o?Math.min(100,paid/o*100):0;return `<div class="debt"><div class="debt-top"><div><div class="debt-name">${esc(d.name)}</div><div class="muted">${Number(d.apr||0).toFixed(2)}% APR · ${esc(d.frequency||'Monthly')}</div></div><div class="amount">${money(c)}</div></div><div class="progress"><span style="width:${p}%"></span></div><div class="progress-copy">${money(paid)} paid of ${money(o)} · ${p.toFixed(0)}% lifetime progress</div>${d.payment?`<div class="chips" style="margin-top:10px"><span class="chip">Payment ${money(d.payment)}</span><span class="chip">${esc(d.frequency)}</span></div>`:''}</div>`}).join(''):'<div class="empty">Add your first debt.</div>'}
function addMonthsSafe(date,n){const d=new Date(date);const day=d.getDate();d.setDate(1);d.setMonth(d.getMonth()+n);d.setDate(Math.min(day,new Date(d.getFullYear(),d.getMonth()+1,0).getDate()));return d}
function occurrences(tx,y,m){if(!tx.date)return[];let d=new Date(tx.date+'T12:00:00');if(isNaN(d))return[];const end=new Date(y,m+1,0,23,59,59),out=[],f=tx.frequency||'One-time';if(f==='One-time')return d.getFullYear()===y&&d.getMonth()===m?[d]:[];let guard=0;while(d<=end&&guard++<1000){if(d.getFullYear()===y&&d.getMonth()===m)out.push(new Date(d));if(f==='Weekly')d=new Date(d.getFullYear(),d.getMonth(),d.getDate()+7,12);else if(f==='Bi-weekly')d=new Date(d.getFullYear(),d.getMonth(),d.getDate()+14,12);else if(f==='Monthly')d=addMonthsSafe(d,1);else if(f==='Quarterly')d=addMonthsSafe(d,3);else if(f==='Yearly')d=new Date(d.getFullYear()+1,d.getMonth(),d.getDate(),12);else break}return out}
function filterTx(t){if(activeFilter==='All')return true;if(activeFilter==='Bills')return t.category==='Bills';if(activeFilter==='Subscriptions')return t.category==='Subscriptions';if(activeFilter==='Debts')return t.category==='Debt Payments';if(activeFilter==='Savings')return t.category==='Savings';if(activeFilter==='Paychecks')return t.type==='income';return true}
function renderCalendar(){const host=$('#calendarHost'),stats=$('#calendarStats'),filters=$('#calendarFilters');if(!host)return;const y=calDate.getFullYear(),m=calDate.getMonth(),first=new Date(y,m,1),days=new Date(y,m+1,0).getDate(),start=(first.getDay()+6)%7,today=new Date();let cells='';for(let i=0;i<start;i++)cells+='<div class="cal-cell outside"></div>';for(let d=1;d<=days;d++){const items=[];state.transactions.forEach(t=>{if(!filterTx(t))return;if(occurrences(t,y,m).some(o=>o.getDate()===d))items.push(t)});const isToday=today.getFullYear()===y&&today.getMonth()===m&&today.getDate()===d;cells+=`<div class="cal-cell ${isToday?'today':''}" data-day="${d}"><div class="cal-num">${d}</div>${items.slice(0,5).map(t=>`<span class="cal-chip ${t.type==='income'?'income':String(t.category||'').toLowerCase().replace(/\s+/g,'-')}">${esc(t.name)} · ${money(t.amount)}</span>`).join('')}</div>`}const monthItems=state.transactions.filter(filterTx);let inc=0,out=0;monthItems.forEach(t=>{const n=occurrences(t,y,m).length;if(t.type==='income')inc+=Number(t.amount||0)*n;else out+=Number(t.amount||0)*n});const balance=sum(state.accounts,a=>a.balance),projected=balance+inc-out;const overdue=state.transactions.filter(t=>t.type!=='income'&&t.date&&new Date(t.date+'T12:00:00')<new Date(today.getFullYear(),today.getMonth(),today.getDate())).length;stats.innerHTML=`<div><small>CURRENT BALANCE</small><strong class="teal">${money(balance)}</strong></div><div><small>PROJECTED BALANCE</small><strong class="pinktext">${money(projected)}</strong></div><div><small>OVERDUE</small><strong class="orange">${overdue}</strong></div><div><small>TODAY IS</small><strong class="lavtext">${today.toLocaleDateString('en-US',{month:'long',day:'numeric'})}</strong></div>`;filters.innerHTML=['All','Bills','Subscriptions','Debts','Savings','Paychecks'].map(x=>`<button type="button" data-filter="${x}" class="${x===activeFilter?'active':''}">${x}</button>`).join('');host.innerHTML=`<div class="month-nav"><button type="button" data-cal="prev">‹ Prev</button><strong>${first.toLocaleDateString('en-US',{month:'long',year:'numeric'})}</strong><button type="button" data-cal="next">Next ›</button></div><div class="weekday-row"><span>Monday</span><span>Tuesday</span><span>Wednesday</span><span>Thursday</span><span>Friday</span><span>Saturday</span><span>Sunday</span></div><div class="big-calendar">${cells}</div>`;host.querySelector('[data-cal=prev]').onclick=()=>{calDate=new Date(y,m-1,1);miniDate=new Date(calDate);renderCalendar();renderMiniCalendar()};host.querySelector('[data-cal=next]').onclick=()=>{calDate=new Date(y,m+1,1);miniDate=new Date(calDate);renderCalendar();renderMiniCalendar()};filters.querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>{activeFilter=b.dataset.filter;renderCalendar()});host.querySelectorAll('.cal-cell[data-day]').forEach(c=>c.onclick=()=>openAddForDate(y,m,Number(c.dataset.day)))}
function openAddForDate(y,m,d){navTo('transactions');const input=$('#transactionForm input[name="date"]');input.value=`${y}-${String(m+1).padStart(2,'0')}-${String(d).padStart(2,'0')}`;input.focus();toast('Date selected ✨')}
function renderMiniCalendar(){const h=$('#miniCalendar');if(!h)return;const y=miniDate.getFullYear(),m=miniDate.getMonth(),first=new Date(y,m,1),days=new Date(y,m+1,0).getDate(),start=(first.getDay()+6)%7,today=new Date();let cells='';for(let i=0;i<start;i++)cells+='<i></i>';for(let d=1;d<=days;d++){const t=today.getFullYear()===y&&today.getMonth()===m&&today.getDate()===d;cells+=`<b class="${t?'today':''}" data-mini-day="${d}">${d}</b>`}h.innerHTML=`<div class="mini-head"><button data-mini="prev">‹</button><strong>${first.toLocaleDateString('en-US',{month:'long',year:'numeric'})}</strong><button data-mini="next">›</button></div><div class="mini-days"><em>M</em><em>T</em><em>W</em><em>T</em><em>F</em><em>S</em><em>S</em>${cells}</div>`;h.querySelector('[data-mini=prev]').onclick=()=>{miniDate=new Date(y,m-1,1);renderMiniCalendar()};h.querySelector('[data-mini=next]').onclick=()=>{miniDate=new Date(y,m+1,1);renderMiniCalendar()};h.querySelectorAll('[data-mini-day]').forEach(b=>b.onclick=()=>{calDate=new Date(y,m,Number(b.dataset.miniDay));navTo('calendar');renderCalendar()})}
function renderAll(){renderDashboard();renderTransactions();renderAccounts();renderSavings();renderDebts();renderCalendar();renderMiniCalendar()}
function bindForms(){$('#transactionForm').addEventListener('submit',e=>{e.preventDefault();const f=new FormData(e.currentTarget);state.transactions.push({id:uid(),name:String(f.get('name')).trim(),amount:Number(f.get('amount')),type:f.get('type'),category:f.get('category'),date:f.get('date'),frequency:f.get('frequency')});saveLocal();e.currentTarget.reset();toast('Planned item saved')});$('#accountForm').addEventListener('submit',e=>{e.preventDefault();const f=new FormData(e.currentTarget);state.accounts.push({id:uid(),name:String(f.get('name')).trim(),type:f.get('type'),balance:Number(f.get('balance'))});saveLocal();e.currentTarget.reset();toast('Account saved')});$('#savingsForm').addEventListener('submit',e=>{e.preventDefault();const f=new FormData(e.currentTarget);state.savings.push({id:uid(),name:String(f.get('name')).trim(),balance:Number(f.get('balance')),goal:Number(f.get('goal'))});saveLocal();e.currentTarget.reset();toast('Savings fund saved')});$('#debtForm').addEventListener('submit',e=>{e.preventDefault();const f=new FormData(e.currentTarget);state.debts.push({id:uid(),name:String(f.get('name')).trim(),originalBalance:Number(f.get('originalBalance')),currentBalance:Number(f.get('currentBalance')),apr:Number(f.get('apr')||0),payment:Number(f.get('payment')||0),frequency:f.get('frequency')});saveLocal();e.currentTarget.reset();toast('Debt saved')})}
function authView(sess){session=sess||null;if(session){$('#authOverlay').classList.add('hidden');$('#signedIn').textContent=`Signed in as ${session.user.email}`;$('#signOutBtn').classList.remove('hidden');pullCloud()}else{$('#authOverlay').classList.remove('hidden');$('#signedIn').textContent='Not signed in';$('#signOutBtn').classList.add('hidden');setSync('Sign in to sync')}}
async function initAuth(){try{const mod=await import('https://esm.sh/@supabase/supabase-js@2');sb=mod.createClient(SUPABASE_URL,SUPABASE_KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});const {data}=await sb.auth.getSession();authView(data.session);sb.auth.onAuthStateChange((_e,s)=>setTimeout(()=>authView(s),0))}catch(e){console.error(e);$('#authMsg').textContent='Login could not load. Refresh and try again.'}}
function bindAuth(){$('#signInBtn').onclick=async()=>{if(!sb)return;const email=$('#email').value.trim(),password=$('#password').value;$('#authMsg').textContent='Signing in…';const {error}=await sb.auth.signInWithPassword({email,password});$('#authMsg').textContent=error?error.message:'Signed in.'};$('#signUpBtn').onclick=async()=>{if(!sb)return;const email=$('#email').value.trim(),password=$('#password').value,msg=$('#authMsg');if(!email){msg.textContent='Enter your email first.';return}if(password.length<6){msg.textContent='Use at least 6 characters.';return}msg.textContent='Creating account…';const {data,error}=await sb.auth.signUp({email,password,options:{emailRedirectTo:location.origin+location.pathname}});if(error){msg.textContent=error.message;return}if(data?.session){msg.textContent='Account created — you’re signed in! 💖';return}msg.className='auth-msg confirm-bubble';msg.innerHTML=`<strong>Hey! 💌 Go confirm your email!</strong><span>We sent a confirmation link to <b>${esc(email)}</b>.</span><span>Come back after confirming and press <b>Sign in</b>.</span>`};$('#signOutBtn').onclick=()=>sb?.auth.signOut()}
function init(){loadLocal();bindForms();bindAuth();renderAll();document.addEventListener('click',e=>{const nav=e.target.closest('[data-nav]');if(nav)navTo(nav.dataset.nav);const add=e.target.closest('[data-action="add-planned"]');if(add){navTo('transactions');$('#transactionForm input[name="name"]').focus()}});$('#mobileMenu').onclick=()=>$('#sidebar').classList.toggle('open');navTo(localStorage.getItem('moneyology:last-section')||'calendar');initAuth();window.addEventListener('focus',()=>{if(session)pullCloud()});document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible'&&session)pullCloud()});if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(console.warn)}
document.addEventListener('DOMContentLoaded',init);