const SUPABASE_URL='https://frvxdqdkoaozuvmrqdkl.supabase.co';
const SUPABASE_KEY='sb_publishable_3SehkvZWuoHkQmTivP6dYw_VIijLcf5';
const LOCAL_KEY='moneyology:standalone:v1';
let sb=null,session=null,syncTimer=null,loadingCloud=false;
let state={transactions:[],debts:[],accounts:[],savings:[],settings:{currency:'$'}};
const $=(s,r=document)=>r.querySelector(s);const $$=(s,r=document)=>[...r.querySelectorAll(s)];
function money(v){return new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(Number(v)||0)}
function uid(){return crypto.randomUUID?crypto.randomUUID():Date.now().toString(36)+Math.random().toString(36).slice(2)}
function loadLocal(){try{const raw=localStorage.getItem(LOCAL_KEY);if(raw)state={...state,...JSON.parse(raw)}}catch(e){console.warn(e)}}
function saveLocal(queue=true){localStorage.setItem(LOCAL_KEY,JSON.stringify(state));renderAll();if(queue)queueSync()}
function setSync(text,kind=''){const el=$('#syncStatus');if(!el)return;el.textContent=text;el.className='sync '+kind}
function toast(text){let el=$('#toast');if(!el){el=document.createElement('div');el.id='toast';el.className='toast';document.body.appendChild(el)}el.textContent=text;el.classList.remove('hidden');clearTimeout(el._t);el._t=setTimeout(()=>el.classList.add('hidden'),2600)}
function queueSync(){if(!session||!sb||loadingCloud)return;clearTimeout(syncTimer);setSync('Saving…','busy');syncTimer=setTimeout(pushCloud,650)}
async function pushCloud(){if(!session||!sb||loadingCloud)return;const {data,error}=await sb.from('user_budget_state').upsert({user_id:session.user.id,payload:state,updated_at:new Date().toISOString()},{onConflict:'user_id'}).select('version,updated_at').single();if(error){console.error(error);setSync('Sync error');return}setSync('Synced','ok')}
async function pullCloud(){if(!session||!sb)return;setSync('Checking cloud…','busy');const {data,error}=await sb.from('user_budget_state').select('payload,updated_at').eq('user_id',session.user.id).maybeSingle();if(error){console.error(error);setSync('Sync error');return}if(data?.payload&&Object.keys(data.payload).length){loadingCloud=true;state={...state,...data.payload};localStorage.setItem(LOCAL_KEY,JSON.stringify(state));loadingCloud=false;renderAll();setSync('Synced','ok')}else{await pushCloud()}}
function navTo(name){$$('.section').forEach(x=>x.classList.toggle('active',x.dataset.section===name));$$('.nav button').forEach(x=>x.classList.toggle('active',x.dataset.nav===name));const b=$(`.nav button[data-nav="${name}"]`);$('#pageTitle').textContent=b?b.textContent.trim():'Moneyology';$('#sidebar').classList.remove('open');localStorage.setItem('moneyology:last-section',name)}
function sum(arr,fn=x=>x){return arr.reduce((a,x)=>a+(Number(fn(x))||0),0)}
function txCategory(t){return t.category||'Other'}
function renderDashboard(){const income=sum(state.transactions.filter(t=>t.type==='income'),t=>t.amount);const out=sum(state.transactions.filter(t=>t.type!=='income'),t=>t.amount);const debt=sum(state.debts,d=>d.currentBalance);const savings=sum(state.savings,s=>s.balance);$('#sumIncome').textContent=money(income);$('#sumOut').textContent=money(out);$('#sumDebt').textContent=money(debt);$('#sumSavings').textContent=money(savings);const recent=[...state.transactions].sort((a,b)=>(b.date||'').localeCompare(a.date||'')).slice(0,5);renderTransactionRows($('#recentTransactions'),recent);const subs=state.transactions.filter(t=>txCategory(t)==='Subscriptions');$('#subscriptionCount').textContent=subs.length}
function renderTransactionRows(host,items){if(!items.length){host.innerHTML='<div class="empty">Nothing here yet.</div>';return}host.innerHTML=items.map(t=>`<div class="row-card"><div><div class="name">${esc(t.name)}</div><div class="meta">${esc(t.category||'Other')} · ${esc(t.frequency||'One-time')} · ${esc(t.date||'No date')}</div></div><div class="amount ${t.type==='income'?'in':'out'}">${t.type==='income'?'+':'-'}${money(t.amount)}</div></div>`).join('')}
function renderTransactions(){renderTransactionRows($('#transactionList'),[...state.transactions].sort((a,b)=>(b.date||'').localeCompare(a.date||'')));renderTransactionRows($('#subscriptionList'),state.transactions.filter(t=>txCategory(t)==='Subscriptions').sort((a,b)=>(a.date||'').localeCompare(b.date||'')))}
function renderDebts(){const host=$('#debtList');if(!state.debts.length){host.innerHTML='<div class="empty">Add your first debt. Moneyology keeps the original balance separate from the current balance so your lifetime progress stays visible.</div>';return}host.innerHTML=state.debts.map(d=>{const original=Math.max(Number(d.originalBalance)||0,0),current=Math.max(Number(d.currentBalance)||0,0),paid=Math.max(original-current,0),pct=original?Math.min(100,paid/original*100):0;return `<div class="debt"><div class="debt-top"><div><div class="debt-name">${esc(d.name)}</div><div class="muted">${d.apr?`${Number(d.apr).toFixed(2)}% APR · `:''}${esc(d.frequency||'Monthly')}</div></div><div class="amount">${money(current)}</div></div><div class="progress"><span style="width:${pct}%"></span></div><div class="progress-copy">${money(paid)} paid of ${money(original)} · ${pct.toFixed(0)}% lifetime progress</div>${d.payment?`<div class="chips" style="margin-top:12px"><span class="chip">Payment ${money(d.payment)}</span><span class="chip">${esc(d.frequency||'Monthly')}</span></div>`:''}</div>`}).join('')}
function renderAccounts(){const host=$('#accountList');host.innerHTML=state.accounts.length?state.accounts.map(a=>`<div class="row-card"><div><div class="name">${esc(a.name)}</div><div class="meta">${esc(a.type||'Account')}</div></div><div class="amount">${money(a.balance)}</div></div>`).join(''):'<div class="empty">No accounts added yet.</div>'}
function renderSavings(){const host=$('#savingsList');host.innerHTML=state.savings.length?state.savings.map(s=>{const pct=s.goal?Math.min(100,(Number(s.balance)||0)/(Number(s.goal)||1)*100):0;return `<div class="debt"><div class="debt-top"><div><div class="debt-name">${esc(s.name)}</div><div class="muted">Goal ${money(s.goal)}</div></div><div class="amount">${money(s.balance)}</div></div><div class="progress"><span style="width:${pct}%"></span></div><div class="progress-copy">${pct.toFixed(0)}% funded</div></div>`}).join(''):'<div class="empty">No savings buckets yet.</div>'}
function renderAll(){renderDashboard();renderTransactions();renderDebts();renderAccounts();renderSavings()}
function esc(s){return String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function bindForms(){
 $('#transactionForm').addEventListener('submit',e=>{e.preventDefault();const f=new FormData(e.currentTarget);state.transactions.push({id:uid(),name:f.get('name').trim(),amount:Number(f.get('amount')),type:f.get('type'),category:f.get('category'),date:f.get('date'),frequency:f.get('frequency')});saveLocal();e.currentTarget.reset();toast('Transaction saved')});
 $('#debtForm').addEventListener('submit',e=>{e.preventDefault();const f=new FormData(e.currentTarget);state.debts.push({id:uid(),name:f.get('name').trim(),originalBalance:Number(f.get('originalBalance')),currentBalance:Number(f.get('currentBalance')),apr:Number(f.get('apr')||0),payment:Number(f.get('payment')||0),frequency:f.get('frequency')});saveLocal();e.currentTarget.reset();toast('Debt saved')});
 $('#accountForm').addEventListener('submit',e=>{e.preventDefault();const f=new FormData(e.currentTarget);state.accounts.push({id:uid(),name:f.get('name').trim(),type:f.get('type'),balance:Number(f.get('balance'))});saveLocal();e.currentTarget.reset();toast('Account saved')});
 $('#savingsForm').addEventListener('submit',e=>{e.preventDefault();const f=new FormData(e.currentTarget);state.savings.push({id:uid(),name:f.get('name').trim(),balance:Number(f.get('balance')),goal:Number(f.get('goal'))});saveLocal();e.currentTarget.reset();toast('Savings bucket saved')});
}
function authView(sess){session=sess||null;const overlay=$('#authOverlay');if(session){overlay.classList.add('hidden');$('#signedIn').textContent=`Signed in as ${session.user.email}`;$('#signOutBtn').classList.remove('hidden');pullCloud()}else{overlay.classList.remove('hidden');$('#signedIn').textContent='Not signed in';$('#signOutBtn').classList.add('hidden');setSync('Sign in to sync')}}
async function initAuth(){try{const mod=await import('https://esm.sh/@supabase/supabase-js@2');sb=mod.createClient(SUPABASE_URL,SUPABASE_KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});const {data}=await sb.auth.getSession();authView(data.session);sb.auth.onAuthStateChange((_e,s)=>setTimeout(()=>authView(s),0))}catch(e){console.error(e);$('#authMsg').textContent='Login could not load. Check your connection and refresh.'}}
function bindAuth(){$('#signInBtn').onclick=async()=>{if(!sb)return;const email=$('#email').value.trim(),password=$('#password').value;$('#authMsg').textContent='Signing in…';const {error}=await sb.auth.signInWithPassword({email,password});$('#authMsg').textContent=error?error.message:'Signed in.'};$('#signOutBtn').onclick=()=>sb?.auth.signOut()}
function init(){loadLocal();renderAll();bindForms();bindAuth();$$('.nav button').forEach(b=>b.onclick=()=>navTo(b.dataset.nav));$('#mobileMenu').onclick=()=>$('#sidebar').classList.toggle('open');navTo(localStorage.getItem('moneyology:last-section')||'dashboard');initAuth();window.addEventListener('focus',()=>{if(session)pullCloud()});document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible'&&session)pullCloud()});if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(console.warn)}
document.addEventListener('DOMContentLoaded',init);